### ISSUE TITLE
Esbjerg as landing point of North Sea Connect and Pangea North

### ISSUE THREAD

**Issue by mikini** [telegeography/www.submarinecablemap.com#10]
What is the source of Esbjerg being specified as the Danish landing point of [North Sea Connect](https://www.submarinecablemap.com/#/submarine-cable/north-sea-connect)?
Aqua Comms themselves [indicate Blaabjerg (Blåbjerg) in their graphics](http://aquacomms.com/our-network/northsea-connect/) though they provide no written mention of it. I've seen Endrup (near Esbjerg) mentioned in local press but I think that is caused by confusion with the landing point of the [COBRAcable being built](https://relined.eu/cobra-kabel) from Holland.

Also Esbjerg (Måde/Maade) is the landing point of the Pangea North cable which is not present in the map at all. See more info https://en.wikipedia.org/wiki/Pangea_(cable_system).

**Comment by krisetya** [comment]
Thank you for your interest.

TeleGeography directly surveys submarine cable operators, annually. Our published info about North Sea Connect landing stations was provided to us by our contact at Aqua Comms earlier this year. Regarding Pangea, our records show that the system is no longer in service.

If you have any further questions or feedback please email us directly at cablemap@telegeography.com.

**Comment by jjonssondk** [comment]
COBRAcable goes a shore at Fanø Island out of Esbjerg. It goes from Fanø, south of Esbjerg to Endrup where EnergiNet operates a powerstation.
It's operated by TenneT, Holland and EnergiNet, Denmark.
https://relined.eu/en/our-networks/dark-fiber-network-denmark/

Esbjerg (Måde) is the landingpoint for Pangea North cable. Landingstation is this address probably owned by Telia now:
https://www.google.com/maps/place/55%C2%B027'33.4%22N+8%C2%B030'08.0%22E/@55.459281,8.5000337,634m/data=!3m2!1e3!4b1!4m14!1m7!3m6!1s0x464b21555f1f8b4b:0xed36a099cdd87bbb!2sM%C3%A5de+Industrivej,+Esbjerg!3b1!8m2!3d55.4636502!4d8.5081469!3m5!1s0x0:0x0!7e2!8m2!3d55.459281!4d8.5022212

Landingpoint for AEC-2 (Havfrue/Mermaid) is probably here:
https://www.google.dk/maps/place/55%C2%B045'09.3%22N+8%C2%B012'48.7%22E/@55.752582,8.2115061,578m/data=!3m2!1e3!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d55.7525816!4d8.2135136

CANTAT-3/TAT-14 same as above but also Telia Carrier here:
https://www.google.dk/maps/place/55%C2%B046'38.5%22N+8%C2%B017'05.7%22E/@55.777359,8.2827383,629m/data=!3m2!1e3!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d55.7773595!4d8.2849275
