### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by LunarTwilight** [telegeography/www.submarinecablemap.com#14]
You can't use the search due to it constantly nuking your search term that you're typing, plus it also adds search as a word in the textarea, so you have to remove it before you can begin to type again.
![2019-03-17_23-07-37](https://user-images.githubusercontent.com/13520392/54512605-9ed80000-4909-11e9-99b7-7e13d31b6e73.gif)

**Comment by krisetya** [comment]
Hi, it would appear that you are attempting to search for a cable that is not on our map. FYI, the Hibernia cable systems have been acquired GTT and renamed GTT Atlantic and GTT Express.

**Comment by LunarTwilight** [comment]
Ah, tho it should probably tell you that you have no results instead of silently nuking what you're typing as soon as you get no results. Also the whole "search is actually put in the textarea" thing still happens.
