### ISSUE TITLE
ACE STP cable landing in wrong location

### ISSUE THREAD

**Issue by mikerjensen** [telegeography/www.submarinecablemap.com#16]
Hi, you have the ACE cable landing in the middle of the sea, near Principe island - i've visited the landing station - it is in Sao Tome island, and actually lands in the same place you have for the Ultramar cable to Annobon (its shares the ACE landing station). 
Mike

**Comment by telegeography** [comment]
Thank you for interest in our map.  We've updated that landing station.  Thanks!

https://www.submarinecablemap.com/#/landing-point/sao-tome-sao-tome-and-principe
