### ISSUE TITLE
License of code?

### ISSUE THREAD

**Issue by joshsimmons** [telegeography/www.submarinecablemap.com#17]
This project is **awesome**, thank you so much all the work that went into it–and for making it source available if not permissively/open source licensed!

I noticed the project lacks a LICENSE file but specifies that the map is made available under CC BY-NC-SA 3.0. Can you clarify whether that license applies to everything in the repo? And, if so, may I suggest adding CC BY-NC-SA to the repo in a LICENSE file to the project root?

Thanks,
Josh

**Comment by telegeography** [comment]
Hey Josh,

>Can you clarify whether that license applies to everything in the repo? 

Yes, the CC BY-NC-SA 3.0 applies to everything in the repo.

>And, if so, may I suggest adding CC BY-NC-SA to the repo in a LICENSE file to the project root?

That's a great idea.  We're going to perform some research and see if this is something we can put together.  

Thanks again,
TeleGeography
