### ISSUE TITLE
NATITUA South cable project missing

### ISSUE THREAD

**Issue by Diego635** [telegeography/www.submarinecablemap.com#18]
There is a project in French Polynesia already approved by the local authorities that will connect two of the Austral Islands (Tubuai and Rurutu) to Tahiti. This project is called NATITUA Sud.

https://actu.fr/politique/australes-l-internet-haut-debit-a-l-etude_34239565.html

**Comment by telegeography** [comment]
Hi,

Thank you for your interest in our map. We're inspecting the article you provided, thank you again.  If you have any other suggestions for updates, additions or fixes for cables or how to make our map more useful please contact cablemap@telegeography.com.

Many thanks,
Team Cable Map
