### ISSUE TITLE
Question: Unstylised data

### ISSUE THREAD

**Issue by BenBE** [telegeography/www.submarinecablemap.com#21]
Is the unstylised raw data available in the repo, or is the repo purely the stylised coordinates for the cable positions?

Is that information also integrated with other projects like e.g. OpenSeaMap / OpenStreetMap?

**Comment by telegeography** [comment]
I'm not sure what you mean by raw data.  The GeoJSON is available here:

https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com/master/public/api/v2/cable/cable-geo.json

and

https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com/master/public/api/v2/landing-point/landing-point-geo.json

Thank you for interest in our map!

**Comment by BenBE** [comment]
With "stylised data" I was referring to the FAQ that at some place mentioned the lines on the map being reduced to straight lines at places. The question was thus mostly for clarification if the GeoJSON contained the full, exact locations, or just the simplified points used on the actual map pictures.

**Comment by telegeography** [comment]
Thank you, I see what you mean.  The GeoJSON lat,longs are "stylised", indeed, this is true.

**Comment by BenBE** [comment]
Could the "raw"/"precise" points be added as a separate set of GeoJSON files too?
