### ISSUE TITLE
right panel box opened for that cable should have an "X" closer button

### ISSUE THREAD

**Issue by jidanni** [telegeography/www.submarinecablemap.com#24]
1. Click a cable
2. The map then greys out and the cable is highlighted.

But the user doesn't know he can click the white area on the map to get back to the original state.

Therefore the right panel box opened for that cable should have an "X" closer button.

**Comment by telegeography** [comment]
Thanks for interest in our map!  We'll take your suggestion into consideration in the next round of updates.  All the best.
