### ISSUE TITLE
APX Central Missing

### ISSUE THREAD

**Issue by virtuallynathan** [telegeography/www.submarinecablemap.com#3]
APX Central seems to be missing:
http://www.subpartners.net/cables/apx-central.html

**Comment by telegeography** [comment]
Hi Nathan, 

Thank you for your interest in our map.  Our best estimates does not put a high degree of likelihood that the Central Cable will be ready on their publicized Ready for Service date on their website. So we are excluding it for the time being.  If you have any other suggestions for updates, additions or fixes for cables or how to make our map more useful please contact cablemap@telegeography.com.

Many thanks,
Team Cable Map
